apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-web-ingress
  labels:
    app: rabbitmq
  annotations:
    alb.ingress.kubernetes.io/group.name: 'internal-alb'
    alb.ingress.kubernetes.io/scheme: 'internal'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:033237185297:certificate/c61cd38f-a877-47bf-9c50-3b6e70c1d944
    alb.ingress.kubernetes.io/ssl-policy: 'ELBSecurityPolicy-TLS13-1-2-2021-06'
spec:
  ingressClassName: alb
  rules:
  - host: rabbitmq.batched.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: rabbitmq
            port:
              number: 15672