name: Scan Workflow

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  scan_test:
    name: Scan Test Pipeline
    uses: LabelTraxx/GitOps/.github/workflows/Scan-Test.yaml@latest
    with:
      SCAN_TYPE: DOCKER
    secrets: inherit
