version = 0.1
[default.deploy.parameters]
stack_name = "self-managed-webhook"
resolve_s3 = true
s3_prefix = "self-managed-webhook"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
