apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: devops-tools-nodeclass
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "amtech-shared-devops-eks-tools"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "amtech-shared-devops-eks"
  role: "AmazonEKSAutoNodeRole"
  tags:
    team: amtech-devops-tools
    karpenterNode: 'true'