apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: devops-tools-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: devops-tools-nodeclass
      taints:
        - key: karpenter.sh/nodepool
          effect: NoExecute
      requirements:
        # - key: "eks.amazonaws.com/instance-category"
        #   operator: In
        #   values: ["t"]
        # - key: "eks.amazonaws.com/instance-generation"
        #   operator: Gt
        #   values: ["2"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["2", "4"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  limits:
    cpu: "40"
    memory: 160Gi
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 10m