apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: ondemand-nodeclass
spec:
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "amtech-shared-devops-eks"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "amtech-shared-devops-eks"
  role: "AmazonEKSAutoNodeRole"
  tags:
    team: amtech-devops
    karpenterNode: 'true'