apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ondemand-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: ondemand-nodeclass
      taints:
        - key: karpenter.sh/nodepool
          effect: NoExecute
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t4g.medium"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
  limits:
    cpu: "6"
    memory: 20Gi